apiVersion: v1
kind: Pod
metadata:
  name: apache-server
spec:
  containers:
    - name: apache-server
      image: ubuntu/apache2
      ports:
        - containerPort: 8080
          protocol: TCP
       