---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: studentcourses
  labels:
    app: studentcoursesapp
    vesion: "1.0"
spec:
  minReadySeconds: 4
  replicas: 2
  selector: 
    matchExpressions:
      - key: app
        operator: In
        values: 
          - studentsapp
  template:
    metadata:
      name: studentcourses
      labels: 
        app: studentsapp     
        version: "1.0"
    spec:
      containers:
        - name: studentappliaction
          image: maheshryali/studentcourses:1.0
          ports:
            - containerPort: 8080
              protocol: TCP      
  
---
apiVersion: v1
kind: Service
metadata:
  name: service  
spec:
  type: ClusterIP
  selector:
    app: studentsapp
    version: "1.0"
  ports:
    - name: witnincluster
      port: 35000
      targetPort: 80    