---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sample-vol
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: gp2
  resources:
    requests:
      storage: 1Gi    

---
apiVersion: v1
kind: Pod
metadata:
  name: alpine-pod
spec:
  containers:
    - name: alpine
      image: alpine:3.17.2
      volumeMounts:
        - mountPath: /
          name: vol-sample
  volumes: 
    - name: vol-sample
      persistentVolumeClaim:
        claimName: sample-vol
        readOnly: false