---
apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: vol-azure
spec:
  accessModes: 
    -ReadWriteOnce
  StorageClassName: managed-premium
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  minReadySeconds: 3
  replicas: 4
  selector:
    matchLabels:
      app: postgres
      version: "v1.0"
  template:
    metadata:
      name: postgres
      labels:
        app: postgres
        version: "v1.0"
    spec:
      containers:
        - name: postgresdata
          image: postgres:alpine3.17
          ports:
            - containerPort: 5432
          protocol: TCP
          env:
            - name: POSTGRES_PASSWORD
              value: password
            - name: POSTGRES_USER
              value: mahesh
            - name: POSTGRES_DB
              value: practicedb
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgresqlvol
  volumes:
    - name: postgresqlvol
      persistentVolumeClaim:      
        claimName: vol-azure
        readOnly: false
---
apiVersion: v1
kind: Service
metadata:
  name: post-svc
spec:
  type: Nodeport
  selector:
    app: postgres
  ports:
    - nodePort: 32003
      port: 35003
      targetPort: 5432    
