---
apiVersion: v1
kind: Service
metadata:
  name: saleordashboardsvc
spec:
  type: NodePort
  selector:
    app: saleordashboard
  ports:
    - name: serviceport
      nodePort: 32001
      port: 35002
      targetPort: 80  