--- 
apiVersion: batch/v1
kind: CronJob
metadata:
  name: alpine-cron
spec:
  schedule: '30 * * * 1-5'
  jobTemplate:
    metadata: 
      name: alpine
    spec:
      backoffLimit: 5
      template:
        metadata:
          name: alpine
          labels:
            app: alpine
        spec:
          containers:
            - name: alpine
              image: alpine:latest
              command:
                - sleep
                - 60s
          restartPolicy: OnFailure          

