---
apiVersion: v1
kind: Namespace
metadata:
  name: dev
  namespace: dev
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-vol
spec:
  accessModes: 
    - ReadWriteMany
  storageClassName: gp2
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: Pod
metadata:
  name: mysql-app
  namespace: dev
spec:
  containers:
    - name: mysql
      image: mysql:8-debian
      ports:
        - containerPort: 3306
          protocol: TCP
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: password
        - name: MYSQL_DATABASE
          value: sampledatabase
        - name: MYSQL_USER
          value: mahesh
        - name: MYSQL_PASSWORD
          value: mahesh  
      volumeMounts:
        - mountPath: /var/lib/mysql
          name: mysql-volume
  volumes:
    - name: mysql-volume
      persistentVolumeClaim:
        claimName: mysql-vol
        readOnly: false




