---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: openmrs
  namespace: health-check
  labels:
    app: openmrs
    version: "1.0"
spec:
  minReadySeconds: 3
  replicas: 2
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - openmrs
  template:
    metadata:
      name: openmrs  
      labels:
        app: openmrs
        version: "1.0"
    spec:
      containers:
        - name: openmrs
          image: 389485504177.dkr.ecr.us-east-1.amazonaws.com/opemmrs:latest
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
      imagePullSecrets:
        - name: regcred      

---
apiVersion: v1
kind: Service
metadata: 
  name: service
spec:
  type: LoadBalancer 
  selector:
    app: openmrs
    version: "1.0"
  ports:
    - name: webport
      targetPort: 8080
      protocol: TCP  
      port: 35010














