---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: gameoflife
  labels:
    app: gameoflife
    version: "1.0"
spec:
  minReadySeconds: 3
  replicas: 2
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - gameoflife
  template:
    metadata:
      name: gameoflife  
      labels:
        app: gameoflife
        version: "1.0"
    spec:
      containers:
        - name: gameoflife
          image: maheshryali/gameoflife:1.0
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata: 
  name: service
spec:
  type: NodePort  
  selector:
    app: gameoflife
    version: "1.0"
  ports:
    - name: webport
      targetPort: 8080
      nodePort: 32500
      protocol: TCP  
      port: 35000














