---
apiVersion: v1
kind: Service
metadata:
  name: student-svc
  namespace: dev
spec:
  type: LoadBalancer
  selector:
    app: studentcourses
  ports:
    - targetPort: 8080  
      port: 35000
      protocol: "TCP"